
const QUARTER_All_YEAR = 'DAT0000000245'
const QUARTER_SUMMER = 'DAT0000000232'
const QUARTER_AUTUMN = 'DAT0000000233'
const QUARTER_WINTER = 'DAT0000000230'
const QUARTER_SPRING = 'DAT0000000231'

const includeQuarters = {
  [QUARTER_All_YEAR]: [QUARTER_SUMMER, QUARTER_AUTUMN, QUARTER_WINTER, QUARTER_SPRING],
  [QUARTER_SUMMER]: [QUARTER_SUMMER, QUARTER_AUTUMN, QUARTER_WINTER, QUARTER_SPRING],
  [QUARTER_AUTUMN]: [QUARTER_AUTUMN, QUARTER_WINTER, QUARTER_SPRING],
  [QUARTER_WINTER]: [QUARTER_WINTER, QUARTER_SPRING],
  [QUARTER_SPRING]: [QUARTER_SPRING],
}

const WORKBENCH_CALL_OUT = 'CALL_OUT'
const WORKBENCH_RECEPTION = 'RECEPTION'
const WORKBENCH_MANAGER = 'MANAGER'

export default {
  QUARTER_All_YEAR,
  QUARTER_SUMMER,
  QUARTER_AUTUMN,
  QUARTER_WINTER,
  QUARTER_SPRING,
  includeQuarters,
  WORKBENCH_CALL_OUT,
  WORKBENCH_RECEPTION,
}
